### ISSUE TITLE
Some errors in console after pressing Ctrl+C (Windows 8)

### ISSUE THREAD

**Issue by Semigradsky** [ddollar/foreman#527] opened 2015-02-13 22:25 UTC
I type `foreman start web` for starting site. After pressing `Ctrl+C` I see this erros in console:

```
C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/foreman-0.77.0/lib/foreman/engine.rb:88:in `rescue in notice_signal': uninitialized constant Errno::EINT (NameError)
        from C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/foreman-0.77.0/lib/foreman/engine.rb:85:in `notice_signal'
        from C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/foreman-0.77.0/lib/foreman/engine.rb:69:in `block (2 levels) in register_signal_handlers'
        from C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/foreman-0.77.0/lib/foreman/engine.rb:412:in `call'
        from C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/foreman-0.77.0/lib/foreman/engine.rb:412:in `wait2'
        from C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/foreman-0.77.0/lib/foreman/engine.rb:412:in `watch_for_termination'
        from C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/foreman-0.77.0/lib/foreman/engine.rb:60:in `start'
        from C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/foreman-0.77.0/lib/foreman/cli.rb:41:in `start'
        from C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/Program Files (x86)/Heroku/ruby-1.9.3/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/Program Files (x86)/Heroku/bin/foreman:9:in `<main>'
```

**Comment by Semigradsky** [comment] 2015-02-13 22:27
Maybe that is solution: #526

**Comment by Wenzil** [comment] 2015-03-18 08:34
Getting the same error. I'm using the same version of foreman (0.77) that comes with Heroku Toolbelt.

**Comment by ddollar** [comment] 2016-04-23 21:31
If anyone that is being affected by this would like to submit a PR I would be grateful. Thank you! My time is currently quite limited so I will likely not be addressing non-critical issues for quite some time.

**Comment by ddollar** [comment] 2016-04-23 21:31
Duplicate of #603

**Closed by ddollar** 2016-04-23 21:31 UTC
Labels: bug
